{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
