apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: floci-jenkins-helm-argocd-gitops
spec:
  description: Production-style monitoring project for Prometheus, Grafana, and Alertmanager

  sourceRepos:
    - https://prometheus-community.github.io/helm-charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: kube-system

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: true
    ignore:
      - group: ""
        kind: Secret
        name: monitoring-admission
      - group: ""
        kind: Secret
        name: grafana-admin-credentials
